/**
 * Backend data layer: RehabChecklistItem
 *
 * ShasthoAI: AI-powered fracture detection + hospital workflow platform.
 * Purpose: Database models/schemas and DB helpers for MongoDB/Firestore integrations.
 *
 * Project-specific notes:
 * - (none)
 */

import mongoose from 'mongoose';

/**
 * RehabChecklistItem
 *
 * Stores completion state for a rehab checklist task.
 * Task keys are generated by the rehab program template.
 */

const RehabChecklistItemSchema = new mongoose.Schema(
  {
    userUid: { type: String, required: true, index: true },
    episodeId: { type: mongoose.Schema.Types.ObjectId, ref: 'InjuryEpisode', required: true, index: true },

    taskKey: { type: String, required: true, index: true },
    done: { type: Boolean, default: true },
    doneAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

RehabChecklistItemSchema.index({ userUid: 1, episodeId: 1, taskKey: 1 }, { unique: true });

export const RehabChecklistItem = mongoose.model('RehabChecklistItem', RehabChecklistItemSchema);
